### ISSUE TITLE
Relative adding of probabilities

### ISSUE THREAD

**Issue by fkarg** [Jugendhackt/paketmagie#10]
currently it's not that unlikely to get probabilities above 1, but that makes no sense, so we should add them Relative and not like we currently do, meaning the probability of 70% at the first tick and 60% at the second tick doesn't get to 130%, but to 88% in total. how it works? you take the 70%, and add to it the result of the 30% that didn't happen in the first tick (1 - 70%) and multiply them with the 60% we have for the second tick, resulting in 70% + 30% \* 60% = 70% + 18% = 88% in total. please fix

**Comment by pajowu** [comment]
If I understood it right, the probability means how high the chance is that a package finds its destination. If that is true why don't you multiply the probabilities?

**Comment by froozen** [comment]
@pajowu We actually do that, but only if the package moves. If the packet is waiting on tick, it could be picked up either the first or the second tick, therefore we have to add the probabilities somehow.

I realy like what @blueburningcoder is proposing. As soon as I've cleaned out my bags, I'll go implement that.

**Comment by fkarg** [comment]
Yes, my idea is for calculating the waiting-probability at the ticks, not the probability at the end since that should be implemented correctly (multiplying), or at least I hope so xDD

**Comment by froozen** [comment]
I just did a little bit of research and came to the conclusion, that @blueburningcoder's solution is correct.

What we want to do is adding two mutually exclusive events, therefore, the first [Addition Rule](http://www.mathgoodies.com/lessons/vol6/conditional.html) (scroll down to **Addition Rule 1**) holds.
