### ISSUE TITLE
Use Data.Graph?

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/paketmagie#18]
https://hackage.haskell.org/package/containers-0.5.6.3/docs/Data-Graph.html

**Comment by froozen** [comment]
`Data.Graph` doesn't really seem fit for what we're doing, as all it has already implemented for us would be the somewhat equivalents of our `TickingGraph` and `edgesFrom`. In that case, I think having more control over our data structures is worth those few extra lines of code.

**Comment by froozen** [comment]
I'll just go ahead and close this one.
