### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by froozen** [Jugendhackt/paketmagie#19]
We also might need to choose a license at some point. I think our options are either something permissive (MIT, BSD) or strict (GPLvN).

**Comment by sternenseemann** [comment]
GPL ftw. (because our application does something useful and it not just irrelevant if somebody uses it without giving stuff back)

**Comment by froozen** [comment]
Agreed. I'd like to use a GPL as well. It'd also honor our README.md.

**Comment by nkoehring** [comment]
I don't like the GPL too much but that's of course your decision. Anyway I would like to see a bit more discussion about it at least. https://tldrlegal.com/ could help you with the possibilities.

**Comment by froozen** [comment]
@nkoehring I personaly think that for an application, the GPL is the most appropriate license, as the only way to use it's source would be building a non-free alternative on top of it and therefore keeping users from getting the rights they deserve. For libraries, on the other hand, I believe more permissive licenses like MIT or BSD3 are acceptable, as they usually aren't direct alternatives to non-free products.

**Comment by froozen** [comment]
We agreed on the GPLv3 license.
This issue is closed as of c9dd9856ce4645b7b888a55b615d0efa4818bbd2.
