### ISSUE TITLE
Correct Spelling mistakes

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/paketmagie#8]
- In the Haskell part we consistently misspelled "Probability" (writing "Propability").
- more?

**Comment by fkarg** [comment]
The in the python code for the parsing needed 'propability' was written that way for compatibility, need to fix it with that one too

**Comment by froozen** [comment]
Seems like `Graph.hs` is free of any "propabilities". I'm sure there a tons of typos in the comments, though.

**Comment by sternenseemann** [comment]
We’ll also to fix the mistakes in the JSON stuff, in the Python code and in Main.hs

NoTimeException here :(

**Comment by fkarg** [comment]
Okay I'll fix the Python part now if it isn't fixed yet, and I'll do it in the master directly, it shouldn't hurt anyone ^^

**Comment by fkarg** [comment]
should be fixed, is now parsing a 'probability' on the output
