### ISSUE TITLE
Fix Main.hs

### ISSUE THREAD

**Issue by sternenseemann** [Jugendhackt/paketmagie#9]
Now we use ticking graph instead of Graph, should break.

**Comment by froozen** [comment]
Shouldn't 58b283a8fb59fe603c6fe5002a82a82bafbc0f0f have resolved this issue?

**Comment by sternenseemann** [comment]
It has, forgot to close, can you pls?

**Comment by froozen** [comment]
This was closed with commit 58b283a.
